'use client';
import Head from 'next/head';
import { useSpring, animated, to } from '@react-spring/web';
import { useGesture } from 'react-use-gesture';
import { useEffect, useMemo, useRef } from 'react';
// import IconEdit from '../components/icons/Edit';
import { FolderPlusIcon } from '@heroicons/react/24/outline';
import { TransformWrapper, TransformComponent } from 'react-zoom-pan-pinch';
import { Dock } from '../components/Dock';
import { DockCard } from '../components/DockCard';
import { useSearchAlbumsQuery } from '../redux/apis/albumAPI';
import { useSession } from 'next-auth/react';
import withAuth from '../components/HOC/withAuth';
import { IAlbum } from '../types/album';
import Album from '../components/Album';

const Home = () => {
  const { data: session } = useSession();
  const { data } = useSearchAlbumsQuery({ token: session?.['accessToken'] });

  useEffect(() => {
    console.log(data);
  }, [data]);
  return (
    <div className={`h-screen w-screen overflow-hidden relative`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-16 mx-auto">
        <div className="grid grid-cols-4 gap-4">
          {data?.map((album: IAlbum) => {
            return <Album key={album?.id} album={album} />;
          })}
        </div>
      </div>
      <Dock>
        <DockCard text="Create Album" key={'create_album'}>
          <FolderPlusIcon className="m-2"></FolderPlusIcon>
        </DockCard>
        <DockCard key={'search_album'}>
          <div>Hello</div>
        </DockCard>
        <DockCard key={'sort_album'}>
          <div>Hello</div>
        </DockCard>
        <DockCard key={'dark_mode'}>
          <div>Hello</div>
        </DockCard>
      </Dock>
    </div>
  );
};

export default withAuth(Home);
